### ISSUE TITLE
Helpdesk ergänzen

### ISSUE THREAD

**Issue by FabianBloch** [c-mahn/hcu-links#2]
Anleitungen, Tickets schreiben über
https://helpdesk.hcu-hamburg.de/

**Comment by c-mahn** [comment]
Bereits vorhanden:
https://github.com/c-mahn/hcu-links/blob/dc2327b15abbbb336386c2b3a84db6d60a2febf9/index.html#L11

**Comment by c-mahn** [comment]
Changed title of link to better reflect changes
