### ISSUE TITLE
Kalender

### ISSUE THREAD

**Issue by FabianBloch** [c-mahn/hcu-links#6]
FSR-Kalender:
https://cloud.hcu-hamburg.de/nextcloud/apps/calendar/p/yAa6iy5ZzjsAJFaq

Abonnement Kalender:
https://cloud.hcu-hamburg.de/nextcloud/remote.php/dav/public-calendars/yAa6iy5ZzjsAJFaq?export

**Comment by c-mahn** [comment]
In Commit #795e76c hinzugefügt.
