### ISSUE TITLE
Mobile / FollowMe printing 

### ISSUE THREAD

**Issue by FabianBloch** [c-mahn/hcu-links#7]
https://print03.ad.hcuhh.de/#/login

**Comment by FabianBloch** [comment]
FollowMe bzw. Anleitung im Wissenschaftsnetz drucken:
https://helpdesk.hcu-hamburg.de/wm/app-SelfServicePortal/search-page/82f66060-9f0c-ec11-2881-005056b3e917_89db5ba7-8a0c-ec11-2881-005056b3e917_01562fa8-1ae1-e511-dd9b-74d02b9d869c/structure/82f66060-9f0c-ec11-2881-005056b3e917

**Comment by c-mahn** [comment]
Ersten Link hinzugefügt. Die Anleitungen sind auch allgemein über "Helpdesk und Anleitungen" erreichbar.
